ui {
	border = 2
	font="RobotoMono Nerd Font 10.5"

	colorscheme {
			background = 0x282C34
			foreground = 0x000000
			selected   = 0xF5E094
			grouped    = 0xFDAF53
			first      = 0xB8E673
			conflict   = 0xED6B32
			insert     = 0xE3C3FA
			active     = 0xeb0000
			inactive   = 0x465457
		}
	}

	outputs {
		"*" {
		background = "/home/bunny/Pictures/wallpapers/hampton_court_green.jpg"
	}
}

inputs {
	pointers {
		"System mouse" = {
		disable-while-typing = true
		accel = 0
		}
	}
	keyboards {
		"*" = {
			xkb = {
				layout = "us,ru"
				options = "grp:win_space_toggle"
			}
		}
	}
}

layouts {
	# main stack
	s = {
		scale = 0.6
		left = single
		right = stack
	}

	f = full
}

actions {
	term = foot
	root = "$HOME/Documents/Code/scripts/hikari/shell root"
	launcher = fuzzel
}

bindings {
	keyboard {
		"L+o" = workspace-show-all
		"L+u" = workspace-cycle-next
		"L+i" = workspace-cycle-prev
	
		"LC+i"      = sheet-show-invisible
		"LC+Period" = sheet-show-all
		"LC+g"      = sheet-show-group

		"L+w" = view-raise
		"L+s" = view-lower
		"LS+o" = view-only
		"LSC+h" = view-hide
		"L+q" = view-quit
		"L+Tab" = view-cycle-next
		"LS+Tab" = view-cycle-prev

		"L+k"   = view-move-up
		"L+j"   = view-move-down
		"L+h"   = view-move-left
		"L+l"   = view-move-right
		"LA+k" = view-increase-size-up
		"LA+j" = view-decrease-size-down
		"LA+l" = view-increase-size-left
		"LA+h" = view-decrease-size-right
		"LS+k"  = view-snap-up
		"LS+j"  = view-snap-down
		"LS+h"  = view-snap-left
		"LS+l"  = view-snap-right
		"L+r"   = view-reset-geometry

		"L+m" = view-toggle-maximize-vertical
		"LS+m"  = view-toggle-maximize-horizontal
		"L+f"     = view-toggle-maximize-full
		"LC+f"    = view-toggle-floating

		# "L+l"      = mode-enter-layout
		# "L+s"      = mode-enter-sheet-assign
		# "L+g"      = mode-enter-group-assign
		# "L+m"      = mode-enter-mark-assign
		# "L+acute"  = mode-enter-mark-select
		# "LS+acute" = mode-enter-mark-switch-select
		# "LCA+g"    = mode-enter-input-grab

		"LCA+r"        = reload

		"L+Return" = action-term
		"L+Apostrophe" = action-term
		"L+d" = action-launcher

		"CA+F1" = vt-switch-to-1
		"CA+F2" = vt-switch-to-2
		"CA+F3" = vt-switch-to-3
		"CA+F4" = vt-switch-to-4
		"CA+F5" = vt-switch-to-5
		"CA+F6" = vt-switch-to-6
		"CA+F7" = vt-switch-to-7
		"CA+F8" = vt-switch-to-8
		"CA+F9" = vt-switch-to-9
	}

	mouse {
		"L+left"  = mode-enter-move
		"L+right" = mode-enter-resize
	}
}

